name: Sync meta-cross to separate repo

on:
  push:
    branches:
      - master
    paths:
      - 'meta-cross/**'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "meta-cross-bot"
          git config --global user.email "bot@banana.com"

      - name: Split meta-cross folder
        run: |
          git subtree split --prefix=meta-cross --branch meta-cross-only

      - name: Push to meta-cross repo
        run: |
          git remote add meta-cross-origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Zahhask45/meta-drivapi.git
          git push meta-cross-origin meta-cross-only:main --force
